### ISSUE TITLE
it always crashed because 'WebRtc.Net.dll'

### ISSUE THREAD

**Issue by mtit** [Phylliida/P2P.NET#2]
Windows 7 x86
VS2012

throw out 'System.BadImageFormatException'

please tell me how to fix this problem

**Comment by mtit** [comment]
![image](https://user-images.githubusercontent.com/12269029/32543975-2501be38-c4b2-11e7-8176-973b1c5405fe.png)
it is chinese  -_-

**Comment by Phylliida** [comment]
Ah it is built for x64, I can upload the x86 version in a bit

**Comment by mtit** [comment]
thanks!

**Comment by Phylliida** [comment]
Sorry for the delay, this should work now :)  You just need to link to the ones in bin/x86 and not the ones in bin/x86_64
